### ISSUE TITLE
Some question...

### ISSUE THREAD

**Issue by wangbiu** [samidhtalsania/lpmln#1]
1. Does the LPMLN in your project coincide with the LPMLN in Lee's Paper "Markov logic style weighted rules under the stable model semantics" ? 
2. Dose the ASP means Answer Set Prolog ?  Syntax defined in this project seems unfamiliar with current ASP core.

**Comment by samidhtalsania** [comment]
1. Yes
2. The syntax does not comprise the entire ASP core but just a subset of it.
